Racism and Sexism
===================
:Author: Chris White
:Email: <cwprogram@live.com>
:Date: 2013-03-16
:Revision: 1.0

== Introduction

Racism and sexism are two major issues in our society that are morally degrading behavior towards a fellow human being. Oddly enough having the last name of "White" has prompted me to think long and hard on these issues. What I often see are these issues being viewed with a more direct approach. If someone makes a racist or sexist comment to another person at their workplace, they can be charged with harassment and fired from their job. However, what has that really gained? Does the person suddenly realize that they were wrong to do so and change their ways? Even worse, what happens if they use the anger of losing their job to further increase their hatred towards the race or gender in question? Now things are *worse* off than before. What we need is education.

== Where is it really coming from?

The larger and more important question here is where is racism and sexism coming from? What makes someone decide that they must devalue another human being? What I often wonder is if these individuals are actually being given a chance to *not* be racist and sexist. Imagine if someone was brought up in St. Louis, which has been noted to be http://www.splicetoday.com/pop-culture/st-louis-the-most-dangerous-racist-city-in-america[a racist city]. More specifically consider the waitress brought up in the article. What made her have the attitude she did? Why did she consider the person of lesser value than the other customers? Did her parents bring her up to think that way? Maybe she just had a run of bad luck with people of that race which caused her to generalize.

On sexism, I often see as a programmer in the IT field the issue of https://adainitiative.org/2012/08/defcon-why-conference-harassment-matters/[women being harassed at conferences]. Take the case of the man with the "punch card". Why did the official security staff member put this individual to the test like this? Did the individual simply give into the pressure from the security staff member, or is there a deeper problem than this? Also interesting to note in this article were many references to "party", "bar", and drunken behavior. Do we need to keep a closer eye on parties, making sure that if parties are held people are there to keep things in check? I ask these questions because if we simply looked at this issue as "the issue with harassment is at the conference", then has the problem really been solved? If the parties were simply left as is wouldn't these occurrences potentially come up again?

== What about good people straying a bit?

Sometimes people who are against racism and sexism can stray off the path a bit. I like to joke with other people because it creates a more comfortable atmosphere, especially if that person is nervous. However as jokes are statements making fun of something, there is the chance that something racist or sexist can be said. I admit that there have been times where I'll make a joke and realized it could be taken as a sexist or racist remark, I just wasn't thinking about it clearly enough. In cases such as these it's necessary to consider again, why did the person do what they did? I've sometimes made comments to people when I see a statement that could be seen as offensive along the lines of "hey I know you didn't mean it this way but be careful because someone might see it this way". This does take some balance though, as you don't want to scare the person into saying nothing at all.

The problem could also be the environment. The individual could be a part of an environment where sexism and racism are strong, and are trying to hold themselves strong in the middle of it all. In this case going after the individual won't solve anything. Instead we need to go after the environment that is causing them to slip without realizing it. They need to be brought back to an environment that supports their beliefs, and allows them to express these beliefs freely.

== What can be done?

As I've mentioned before it's about education. It also needs to be addressed at the lowest level possible. Our education system is where individuals will build their core values. Yet, in my academic lifetime I've never seen a required class addressing the issues of sexism and racism. How will the youth realize that sexism and racism are wrong if no one puts it front and center while they are developing their critical thinking frameworks? It also needs to happen on the family level. Children need to be made aware that these issues exist and why they shouldn't partake in racism and sexism. It also needs to be strong a well. When children are put into school, they will start spending a lot of time away from there parents. During this time they will have to deal from various external pressures as they figure out what kind of person they are. If these pressure are stronger than the values instilled by parents, the individual may give into the pressure and turn towards racism and sexism.

== It will not happen overnight

No one is going to walk into St. Louis and magically rid of racism, nor is anyone going to suddenly make sexism disappear from conferences. This takes time, and in the battle against sexism and racism there needs to be persistence about it. In fact it may take generations for change to occur as beliefs are slowly adjusted towards the right path. I'm interested to see what the effects of the Internet will be on helping, or perhaps even harming the spread of the anti-racism and anti-sexism causes by exposing people to different beliefs.

== Should we suffer for our beliefs?

One day I walked into a convenience store in Tokyo, Japan. Upon entering a stranger walked up to me and asked "Do you know why I hate you?" At the time my beliefs were not as strong as they were now, so I had no idea how to respond. There were other cases where I felt like a lesser person while I was there. However I know that not all of Japan is like this. Every year I take a trip there, knowing that I can run into this racism, that I could suffer. Even so I still keep going, because I believe that this can stop. Why? Because there are friends I talk to in Japan that want to know more about Western culture, and want to understand different ways of thinking. If I can impact them, it will help them spread the word, and the message against racism spreads further.

When faced with being a victim of racism or sexism, the individual needs to ask themselves, "should I continue partaking in actions that result in my further discrimination?" Should they suffer to further their beliefs? The answer to this will not always be "yes". On the topic of the woman who was touched inappropriately at DEFCON, I have no idea how that impacted her. I would certainly not pressure her to keep going to conferences if it caused her negative mental effects. What I really want is people to weigh the costs and benefits to guarding personal beliefs.

== The illusion of success

I would like to conclude with something that has always bothered me, which is what I call the "illusion of success". Morgan Freeman's http://www.youtube.com/watch?v=GeixtYS-P3s[stance on Black History Month] best sums up this issue. At one point on Twitter someone was talking about how International Women's Day was a great thing. However the fact that we need it is actually a *bad thing*. We shouldn't need a day like this because *women should be respected as fellow beings regardless*. They should not need a day set aside so that people realize their importance. The battle has not been won until we only have a "humanity day", and that should be everyday. Until then we need days like this to show people the possibility of change, and work towards improving the future.
