Revenge and The Fear Marketplace
================================
:Author: Chris White
:Email: <cwprogram@live.com>
:Date: 2013-04-19

== Introduction ==

The week of April 15th has been one of great sorrow and difficulty. When looking over Twitter and Facebook, I have seen mixed reactions to one of the tragedies: The Boston Marathon. A river of vengeance floods through, bringing with it cries of justice, calls for the death of the suspects. In the midst of all this I sit a minority, wondering what vengeance really accomplishes, and consider difficult ethical questions. Minority as it may be, I wish to present my view in hopes that it may change the minds of at least a few.

== The Root Of Evil ==

What is the root of all evil? What is the root of all good? Interestingly enough the answer is the same. The root of both is humanity and the free will bestowed upon it. All evil could be destroyed through the destruction of free will, or the removal of the human race off the face of the earth. However, free will is what makes humans what they are. Destroying the human race is something that very few would agree as being a good option.

Yet, free will is at the same time a source of good. Often the presence of good is taken for granted. Evil is the extreme, and emphasized accordingly. In fact, if there is no evil then there is no good, as good is the lack of evil. Instead it would simply be a state of perfect existence. Rather boring in the human sense. However evil is still damaging to humanity, so what is to be done about it?

== Let Me Show You Fear ==

Do you consider the Boston Marathon bombing fear? No, that is only the beginning of the story. You see, a terrorist has a specific objective in mind with their actions. They want the subject to be afraid. They want the subject to be unable to continue with their daily lifestyle. It's a mental breakdown in effect. So a terrorist bombs a large marathon causing injury and death. Now the hunt for the suspect is on.

For such atrocities, a call for the death of the person responsible. It is meant to "bring justice". I do wonder how many people actually wanted the bombing suspects alive. Why would you want such a horrible person alive? Well here-in lies the problem. The death of a terrorist brings with it many mixed messages.

The greatest of all is that it is the ultimate showcase of fear. Someone is feared so much that people fear the individual's *actual existence*. Another terrorist sees this and confirms that it is the best way to instill fear. So it simply gets repeated. In many cases the death of a terrorist actual is *beneficial* to them. http://www.economist.com/node/2329785[Suicide bombing] is a prime example of such cases. It is considered to be the greatest contribution to a cause for some of the individuals that partake in these acts.

== Turn The Public Into Terrorists ==

Now to consider a different instance of terror. After the 9/11 attacks, something quite horrible happened. Some of the public were turned into terrorists themselves in their quest for justice. A study was done in 2012 http://quod.lib.umich.edu/j/jmmh/10381607.0007.101?rgn=main;view=fulltext[on the attitudes towards Muslim Americans post 9/11]. In particular the study noted that "In situations where Muslim Americans were boarding a plane, higher negative attitudes were present". These sentiments often turn ugly, with reports of http://www.splcenter.org/get-informed/news/splc-testifies-about-increase-in-anti-muslim-bias/anti-muslim-incidents-since-9-11#.UXHVFJBc3PQ[many anti-Muslim crimes since 9/11]. Looking at some of the events:

- Brent D. Seever, 38, was sentenced to life in prison for killing an Arab-American man after the 9/11 terrorist attacks
- Jesse J. Mason, 24, was arrested after allegedly throwing furniture and smashing a window at a residence of two men he believed were of Middle Eastern descent while yelling, “This is America — Arabs and al-Qaida out of the country.” Mason also allegedly had spit on the two men a few days earlier and made similar remarks in front of a bar.
- Several Asian men shouted ethnic slurs and allegedly assaulted a man of Asian-Indian descent who they thought was Middle Eastern.

Congratulations members of the public, you have now become what you so despise.

== Pick Your Fear ==

Behind the scenes there is something fostering all this. Something we take for granted every day. That is the media in all its forms. If you're into fear it's all quiet convenient really. There is a wide variety of fear for you to pick from in the fear marketplace. One source may provide you with the finest wares of speculation. Perhaps you're not quite feeling that today. Oh don't worry, there are plenty of channels to show continual footage of the disaster and remind you that you should remember to stay afraid!

== Where There Is Evil, There Is Good ==

Fear and evil can only be reversed by good and compassion. Consider this if you will, how many of you saw the bombing and immediately asked yourself "how can I help?" I must admit I got a little caught up by the events around me, simply trying to assess what had actually happened. However upon walking away from Twitter for I bit, I asked if there were places to donate to. No response at all. Were people were too preoccupied with fear to notice? Who can really tell. I had to search on my own and ended up finding that the http://www.bmc.org/[Boston Medical Center] had housed some of the victims. So I donated to them. I could have loathed in anger towards the suspect, but that will not help http://www.necn.com/04/16/13/19-patients-still-at-Boston-Medical-Cent/landing.html?blockID=837941&feedID=11106[the many still in need of care].

It can not be forgotten that in the face of disaster, good still remains. Consider for a moment the many who went to provide aid, including http://www.metro.us/newyork/news/national/2013/04/17/carlos-arredondo-boston-marathon-hero-with-the-cowboy-hat/[Carlos Arredondo], who helped an injured victim into a wheelchair and transported him to safety. The American Red Cross http://www.redcross.org/news/press-release/Red-Cross-Response-to-the-Boston-Marathon-Explosions[provided blood donations and mental care support to victims]. http://newsfeed.time.com/2013/04/18/therapy-dogs-arrive-in-boston-to-comfort-survivors-of-marathon-bombing/[Therapy dogs] were brought in to provide additional comfort to those that needed it. Social site reddit worked http://www.huffingtonpost.com/2013/04/16/random-acts-of-pizza-boston-reddit-marathon_n_3094151.html[to send pizza to shelters, hospitals, and other locations].  The Boston government, in collaboration with many businesses setup https://onefundboston.org/[The One Fund Boston] to help victims. To quote the site's statement:

++++
<blockquote>
Within an hour, I had calls from business leaders and local
philanthropists who, like me, were heartbroken by the impact this hideous
tragedy has had on individuals, their families, and friends. And they want to
do everything they can to help these people physically and psychologically in
the future.
</blockquote>
++++

== Where Is The Real Problem? ==

It is important to understand that terrorism is a symptom of a problem. If you kill the suspect, it's very difficult to understand what the symptom was. If we don't know what the symptom is, how will we know how to prevent similar occurrences in the future? Someone else could simply take the suspect's place to continue whatever cause lead to the bombings in the first place. There also a certain amount of scientific background on http://www.scientificamerican.com/article.cfm?id=anger-management-self-control[what drives people to kill]. By keeping the bomber alive, there is a chance we can learn something from the individual that could help prevent people resorting to violence.

== Is There Forgiveness? ==

Consider this for a moment: Could the Boston Marathon bomber ever be forgiven? I believe in our society that forgiveness is often forgotten. Imagine if you will, there were a way to turn the bomber into someone that volunteered to help the less fortunate. Maybe as part of the prison sentence the person does community service. Imagine if we were able to show future generations the hope of humanity, by taking a ruthless bomber and turning them around to do good for people? Instead we will live in a society that wants to take the bomber's life, to show that there is a certain point of no hope. That is not the kind of society I want for future generations.

== What Can We Do? ==

We, as human beings, need to look out for each other. We need to help others in need, and not give into hatred. When faced with fear we need to respond with compassion towards others. Go out and volunteer, donate to charitable causes, help out those in need around you, show everyone that the world is not completely full of disaster. Do not let the media decide for you what you should fear. Take a hold of your life and make the world a better place for all. Change your mindset to feel forgiveness, so that hope is not completely destroyed. That is how we can win against evil.
